name: GO WEB CLI

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test-and-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'
      - name: Install Denpendencies
        run: go mod download
      
      - name: Run Unit Test
        run: go test ./...
      
      - name: Run Benchmarks (Pressure Test)
        run: go test -bench=. -benchmem ./...

      - name: Build Application And Run Server
        run: |
          go build -o main ./cmd
          ./main & # 在后台启动 Go Web 服务
          sleep 5  # 等待几秒确保服务完全启动

      - name: Run k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load-test.js
          

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-binary
          path: main